Repository one-acre-fund/ussd-sms, pull requests merged in 2021-03, with the labels that each got.

#304 HOTFIX-ESWFA-102 switching on the kenya impact trainings
  CHANGELOG.md
  ke-legacy/main.js
  kenya-trainings-menu/options.js
  package-lock.json
  package.json
Labels: size/M

#301 ESWFA-93 Add an IPP option to the non farmer USSD menu
  CHANGELOG.md
  contact-call-center/contactCallCenter.test.js
  contact-call-center/menuOptions.js
  package-lock.json
  package.json
Labels: size/S

#305 MOB-407-Handle invalid shs
  CHANGELOG.md
  package-lock.json
  package.json
  shs/endpoints/registerSerial.js
Labels: size/XS

#306 HOT-FIX: THD-5670-Switching on of Training service on USSD & 2-Way SMS
  CHANGELOG.md
  ke-legacy/main.js
  kenya-impact-trainings/inputHandlers/phoneNumberHandler.js
  kenya-impact-trainings/inputHandlers/phoneNumberHandler.test.js
  kenya-impact-trainings/kenya-impact-trainings.js
  kenya-impact-trainings/kenya-impact-trainings.test.js
  kenya-impact-trainings/translations/index.js
  kenya-impact-trainings/utils/makePhones.js
  kenya-impact-trainings/utils/makePhones.test.js
  kenya-trainings-menu/options.js
  package-lock.json
  package.json
Labels: size/L

#307 HOT-FIX ESWFA-113 Fix the Kenya Impact Trainings
  CHANGELOG.md
  ke-legacy/main.js
  kenya-impact-trainings/inputHandlers/phoneNumberHandler.js
  kenya-impact-trainings/inputHandlers/phoneNumberHandler.test.js
  kenya-impact-trainings/kenya-impact-trainings.test.js
  kenya-impact-trainings/translations/index.js
  kenya-impact-trainings/utils/TrainingTriggeredText.js
  kenya-impact-trainings/utils/TrainingTriggeredText.test.js
  kenya-trainings-menu/options.js
  package-lock.json
  package.json
Labels: size/M

#308 Fixing popup translation
  kenya-impact-trainings/translations/index.js
Labels: size/XS

#309 MOB-408 Change shs displaying message
  CHANGELOG.md
  package-lock.json
  package.json
  shs/endpoints/registerSerial.js
  shs/serial-number-handler/serialNumberHandler.js
  shs/serial-number-handler/serialNumberHandler.test.js
  shs/shs.js
  shs/translations.js
Labels: size/M
