Repository one-acre-fund/ussd-sms, pull requests merged in 2021-04, with the labels that each got.

#310 ESWFA-92 Malawi USSD Balance check
  CHANGELOG.md
  malawi/MalawiMain.js
  malawi/MalawiMain.test.js
  malawi/checkBalance/checkBalance.js
  malawi/checkBalance/checkBalance.test.js
  malawi/checkBalance/inputHandlers/nextScreenBalance.js
  malawi/checkBalance/inputHandlers/nextScreenBalance.test.js
  malawi/checkBalance/translations/index.js
  malawi/inputHandlers/accountNumberInputHandler.js
  malawi/inputHandlers/accountNumberInputHandler.test.js
  malawi/inputHandlers/inputHandlers.js
  malawi/inputHandlers/inputHandlers.test.js
  malawi/inputHandlers/mainMenuHandler.js
  malawi/inputHandlers/mainMenuHandler.test.js
  malawi/inputHandlers/registerInputHandlers.js
  malawi/inputHandlers/registerInputHandlers.test.js
  malawi/translations/index.js
  malawi/utils/getClient.js
  malawi/utils/getClient.test.js
  malawi/utils/menuOptions.js
  malawi/utils/onAccountNumberValidated.js
  malawi/utils/onAccountNumberValidated.test.js
Labels: size/L

#311 Eswfa 81 check group code
  CHANGELOG.md
  rw-legacy/core.js
  rw-legacy/enrollment.js
  rw-legacy/lib/enr-check-gid.js
  rw-legacy/lib/utils/message-translations.js
Labels: size/M

#318 Bi2 593 missing data points
  CHANGELOG.md
  notifications/elk-notification/elkNotification.js
  package-lock.json
  package.json
  shs/serial-number-handler/serialNumberHandler.js
  shs/shs.js
Labels: size/S
