Repository one-acre-fund/ussd-sms, pull requests merged in 2021-02, with the labels that each got.

#252 MOB-73 send multiple mm receipts
  CHANGELOG.md
  package-lock.json
  package.json
  repayments/repayments.js
  repayments/repayments.test.js
Labels: size/L

#293 Mob 135 shs registration part2
  CHANGELOG.md
  ke-legacy/main.js
  package-lock.json
  package.json
  rw-legacy/core.js
  shs/account-number-handler/accountNumberHandler.js
  shs/account-number-handler/accountNumberHandler.test.js
  shs/endpoints/getCode.js
  shs/endpoints/getCode.test.js
  shs/endpoints/registerSerial.js
  shs/endpoints/registerSerial.test.js
  shs/gL-menu-handler/gLMenuHandler.js
  shs/gL-menu-handler/gLMenuHandler.test.js
  shs/get-code-serial-handler/getCodeSerialHandler.js
  shs/get-code-serial-handler/getCodeSerialHandler.test.js
  shs/helper-functions/getCode.js
  shs/helper-functions/getCode.test.js
  shs/helper-functions/registerSerialNumber.js
  shs/helper-functions/registerSerialNumber.test.js
  shs/registration-type-handler/registrationTypeHandler.js
  shs/registration-type-handler/registrationTypeHandler.test.js
  shs/replacement-handler/replacementHandler.js
  shs/replacement-handler/replacementHandler.test.js
  shs/request-code-handler/requestCodeHandler.js
  shs/request-code-handler/requestCodeHandler.test.js
  shs/serial-number-handler/serialNumberHandler.js
  shs/serial-number-handler/serialNumberHandler.test.js
  shs/shs-menu-handler/shsMenuHandler.js
  shs/shs-menu-handler/shsMenuHandler.test.js
  shs/shs-type-handler/shsTypeHandler.js
  shs/shs-type-handler/shsTypeHandler.test.js
  shs/shs.js
  shs/shs.test.js
  shs/translations.js
Labels: size/XXL

#296 HOTFIX: fixing the pshop shs activation
  CHANGELOG.md
  package-lock.json
  package.json
  rw-legacy/lib/psh-reg-check.js
  rw-legacy/lib/psh-renew-code.js
  rw-legacy/lib/psh-serial-verify.js
Labels: size/M

#297 HotFix-add logging on shs service
  CHANGELOG.md
  package-lock.json
  package.json
  shs/endpoints/getCode.js
  shs/endpoints/getCode.test.js
  shs/endpoints/registerSerial.js
  shs/endpoints/registerSerial.test.js
Labels: size/S

#298 Hot fix addtional logging
  shs/endpoints/getCode.js
  shs/endpoints/registerSerial.js
Labels: size/S

#300 HOTFIX-MOB-405-MOB-406-add call vars for elk and changed payment calculation shs
  CHANGELOG.md
  package-lock.json
  package.json
  shs/helper-functions/getCode.js
  shs/helper-functions/getCode.test.js
  shs/helper-functions/registerSerialNumber.js
  shs/helper-functions/registerSerialNumber.test.js
  shs/shs.js
  shs/translations.js
Labels: size/M

#302 HOT-FIX ESWFA-53 Monitoring tool for Telerivet to track USSD downtime from Africa's talking in Rwanda
  CHANGELOG.md
  package-lock.json
  package.json
  rw-legacy/traffic-alert.js
Labels: size/XS
