Repository one-acre-fund/ussd-sms, pull requests merged in 2021-05, with the labels that each got.

#316 adding the group leader check in registration
  CHANGELOG.md
  client-registration/clientRegistration.js
  rw-legacy/core.js
  rw-legacy/dat/district-bundles.js
  rw-legacy/enrollment.js
  rw-legacy/lib/enr-client-logger.js
  rw-legacy/lib/enr-get-product-options.js
  rw-legacy/lib/get-menu-option.js
  rw-legacy/lib/populate-input-menu-by-district.js
  rw-legacy/lib/roster/register-client.js
  rw-legacy/lib/utils/message-translations.js
Labels: size/XXL

#321 Master back merge
  CHANGELOG.md
  client-registration/clientRegistration.js
  ke-legacy/main.js
  notifications/elk-notification/elkNotification.js
  package-lock.json
  package.json
  repayments/repayments.test.js
  sbcc/translations/message-translations.js
  sbcc/ussd/input-handlers/nationalIdHandler.js
  sbcc/ussd/input-handlers/nationalIdHandler.test.js
  sbcc/ussd/input-handlers/pinHandler.js
  sbcc/ussd/input-handlers/pinHandler.test.js
  sbcc/ussd/input-handlers/pinMenuHandler.js
  sbcc/ussd/input-handlers/pinMenuHandler.test.js
  sbcc/ussd/input-handlers/sbccMenuHandler.js
  sbcc/ussd/input-handlers/sbccMenuHandler.test.js
  shs/serial-number-handler/serialNumberHandler.js
  shs/shs.js
Labels: size/XXL

#325 Deployment 05-05-21
  CHANGELOG.md
  client-registration/clientRegistration.js
  malawi/MalawiMain.js
  malawi/MalawiMain.test.js
  malawi/checkBalance/checkBalance.js
  malawi/checkBalance/checkBalance.test.js
  malawi/checkBalance/inputHandlers/nextScreenBalance.js
  malawi/checkBalance/inputHandlers/nextScreenBalance.test.js
  malawi/checkBalance/translations/index.js
  malawi/inputHandlers/accountNumberInputHandler.js
  malawi/inputHandlers/accountNumberInputHandler.test.js
  malawi/inputHandlers/inputHandlers.js
  malawi/inputHandlers/inputHandlers.test.js
  malawi/inputHandlers/mainMenuHandler.js
  malawi/inputHandlers/mainMenuHandler.test.js
  malawi/inputHandlers/registerInputHandlers.js
  malawi/inputHandlers/registerInputHandlers.test.js
  malawi/translations/index.js
  malawi/utils/getClient.js
  malawi/utils/getClient.test.js
  malawi/utils/menuOptions.js
  malawi/utils/onAccountNumberValidated.js
  malawi/utils/onAccountNumberValidated.test.js
  package-lock.json
  repayments/repayments.test.js
  rw-legacy/core.js
  rw-legacy/dat/district-bundles.js
  rw-legacy/enrollment.js
  rw-legacy/lib/enr-check-gid.js
  rw-legacy/lib/enr-client-logger.js
  rw-legacy/lib/enr-get-product-options.js
  rw-legacy/lib/get-menu-option.js
  rw-legacy/lib/populate-input-menu-by-district.js
  rw-legacy/lib/roster/register-client.js
  rw-legacy/lib/utils/message-translations.js
  sbcc/translations/message-translations.js
Labels: size/XXL

#327 HOTFIX: Enabling all bundles to be added on the list
  rw-legacy/dat/district-bundles.js
  rw-legacy/lib/get-menu-option.js
  rw-legacy/lib/populate-input-menu-by-district.js
Labels: size/M

#326 Fixing the Pshops
  rw-legacy/dat/district-bundles.js
  rw-legacy/pshops.js
Labels: size/XS

#329 HOTFIX-ESWFA-166 Refactor Rwanda ussd script module
  CHANGELOG.md
  avocado-trees-ordering/avocadoTreesOrdering.js
  chicken-services/chickenServices.js
  client-registration/clientRegistration.js
  group-repayments/groupRepayments.js
  package-lock.json
  package.json
  rw-legacy/core.js
  rw-legacy/lib/enr-resume-registration.js
  rw-legacy/lib/enr-retrieve-client-row.js
  rw-legacy/lib/enr-send-order-sms.js
  rw-legacy/lib/populate-menu.js
  transaction-history/transactionHistory.js
Labels: size/L

#330 Backmerge 24 05
  CHANGELOG.md
  avocado-trees-ordering/avocadoTreesOrdering.js
  chicken-services/chickenServices.js
  client-registration/clientRegistration.js
  group-repayments/groupRepayments.js
  package-lock.json
  package.json
  rw-legacy/core.js
  rw-legacy/lib/enr-resume-registration.js
  rw-legacy/lib/enr-retrieve-client-row.js
  rw-legacy/lib/enr-send-order-sms.js
  rw-legacy/lib/get-menu-option.js
  rw-legacy/lib/populate-input-menu-by-district.js
  rw-legacy/lib/populate-menu.js
  rw-legacy/pshops.js
  transaction-history/transactionHistory.js
Labels: size/L

#332 Ser 525 log receipts failure
  CHANGELOG.md
  logger/elk/elk-logger.js
  mobile-money-receipts/main.js
  mobile-money-receipts/main.test.js
  package-lock.json
  package.json
  repayments-rw/repaymentsRw.js
  repayments-rw/repaymentsRw.test.js
  repayments/repayments.js
  repayments/repayments.test.js
Labels: size/L

#335 remove underscore
  logger/elk/elk-logger.js
Labels: size/XS
