Repository one-acre-fund/ussd-sms, pull requests merged in 2021-08, with the labels that each got.

#386 adding unit tests to the ussd google message script
  regions_handler/ussd_google_message_script.test.js
Labels: size/S

#384 USSD Menu Update v1 ||| ChangeLog Updated
  CHANGELOG.md
  ke-legacy/main.js
  regions_handler/ussd_google_message_script.js
  regions_handler/ussd_google_message_script.test.js
Labels: size/L

#380 Eswfa 199 pshop client registration
  CHANGELOG.md
  pshopRegistration/inputHandlers/districtHandler.js
  pshopRegistration/inputHandlers/districtHandler.test.js
  pshopRegistration/inputHandlers/groupHandler.js
  pshopRegistration/inputHandlers/groupHandler.test.js
  pshopRegistration/inputHandlers/sectorHandler.js
  pshopRegistration/inputHandlers/sectorHandler.test.js
  pshopRegistration/inputHandlers/sitesHandler.js
  pshopRegistration/inputHandlers/sitesHandler.test.js
  pshopRegistration/pshopRegistration.js
  pshopRegistration/pshopRegistration.test.js
  pshopRegistration/translations/index.js
  pshopRegistration/utils/OnValidatedFactory.js
  pshopRegistration/utils/OnValidatedFactory.test.js
  pshopRegistration/utils/getDistrictsMenu.js
  pshopRegistration/utils/getDistrictsMenu.test.js
  pshopRegistration/utils/getGroupsMenu.js
  pshopRegistration/utils/getGroupsMenu.test.js
  pshopRegistration/utils/getSectorsMenu.js
  pshopRegistration/utils/getSectorsMenu.test.js
  pshopRegistration/utils/getSitesMenu.js
  pshopRegistration/utils/getSitesMenu.test.js
  pshopRegistration/utils/registerClient.js
  pshopRegistration/utils/registerClient.test.js
  rw-legacy/lib/utils/message-translations.js
  rw-legacy/pshops.js
  shared/createMenu.js
  shared/createMenu.test.js
  shared/rosterApi/getClient.js
Labels: size/XL

#344 ESWFA-119 Rwanda SHS
  CHANGELOG.md
  ke-legacy/main.js
  rw-legacy/core.js
  shared/getCurrentDate.js
  shared/getCurrentDate.test.js
  shs/account-number-handler/accountNumberHandler.js
  shs/account-number-handler/accountNumberHandler.test.js
  shs/get-code-serial-handler/getCodeSerialHandler.js
  shs/get-code-serial-handler/getCodeSerialHandler.test.js
  shs/helper-functions/clientTestData.js
  shs/helper-functions/getCode.js
  shs/helper-functions/getCode.test.js
  shs/helper-functions/getKeyCodeRequest.js
  shs/helper-functions/getKeyCodeRequest.test.js
  shs/helper-functions/getShsPrice.js
  shs/helper-functions/getShsPrice.test.js
  shs/helper-functions/getkeyCodeType.js
  shs/helper-functions/getkeyCodeType.test.js
  shs/helper-functions/registerSerialNumber.js
  shs/helper-functions/registerSerialNumber.test.js
  shs/request-code-handler/requestCodeHandler.js
  shs/shs-menu-handler/shsMenuHandler.js
  shs/shs-type-handler/shsTypeHandler.js
  shs/translations.js
Labels: size/XXL

#351 finalizing the seed germination and readding it to the kenya core menu
  ke-legacy/utils/menus/populate-menu/nonClientMainMenu.js
  seed-germination-issues/inputHandlers/customSeedBrandInputHandler.js
  seed-germination-issues/inputHandlers/customSeedBrandInputHandler.test.js
  seed-germination-issues/inputHandlers/customSeedVarietyInputHandler.js
  seed-germination-issues/inputHandlers/customSeedVarietyInputHandler.test.js
  seed-germination-issues/inputHandlers/dukaInputHandler.js
  seed-germination-issues/inputHandlers/dukaInputHandler.test.js
  seed-germination-issues/inputHandlers/lotCodeInputHandler.js
  seed-germination-issues/inputHandlers/lotCodeInputHandler.test.js
  seed-germination-issues/inputHandlers/monthInputHandler.js
  seed-germination-issues/inputHandlers/monthInputHandler.test.js
  seed-germination-issues/inputHandlers/phoneNumberInputHandler.js
  seed-germination-issues/inputHandlers/phoneNumberInputHandler.test.js
  seed-germination-issues/inputHandlers/plantingDateInputHandler.js
  seed-germination-issues/inputHandlers/plantingDateInputHandler.test.js
  seed-germination-issues/inputHandlers/registerInputHandlers.js
  seed-germination-issues/inputHandlers/registerInputHandlers.test.js
  seed-germination-issues/inputHandlers/seedBrandInputHandler.js
  seed-germination-issues/inputHandlers/seedBrandInputHandler.test.js
  seed-germination-issues/inputHandlers/seedVarietyInputHandler.js
  seed-germination-issues/inputHandlers/seedVarietyInputHandler.test.js
  seed-germination-issues/inputHandlers/severityInputHandler.js
  seed-germination-issues/inputHandlers/severityInputHandler.test.js
  seed-germination-issues/inputHandlers/weekInputHandler.test.js
  seed-germination-issues/seedGerminationIssues.js
  seed-germination-issues/seedGerminationIssues.test.js
  seed-germination-issues/translations/index.js
Labels: size/XL

#376 THD-6616 government services
  CHANGELOG.md
  rw-legacy/extension-survey.js
  rw-legacy/lib/ext-answer-verify.js
  rw-legacy/lib/ext-ask-question.js
  rw-legacy/lib/ext-vid-verify.js
  rw-legacy/lib/utils/message-translations.js
  tester-pack/confirmation/inputHandlers/receptionHandler.js
  tester-pack/confirmation/inputHandlers/receptionHandler.test.js
  tester-pack/inputHandlers/testerPackMenuHandler.js
  tester-pack/inputHandlers/testerPackMenuHandler.test.js
  tester-pack/testerPack.test.js
  tester-pack/translations/index.js
Labels: size/L

#388 Back merge 09 aug 2021
  CHANGELOG.md
  chicken-services/check-chicken-cap-by-district/CheckChickenCapByDistrict.js
  chicken-services/chicken-eligibility/chickenEligibility.js
  package-lock.json
  package.json
  rw-legacy/pshops.js
  tz-legacy/TanzaniaMain.js
Labels: size/S

#394 HOT-FIX: changing the translation for pshop client registration
  CHANGELOG.md
  rw-legacy/lib/utils/message-translations.js
Labels: size/XS

#397 Consolidated Database v1
  CHANGELOG.md
  ke-legacy/main.js
  regions_handler/ussd_google_message_script.js
  regions_handler/ussd_google_message_script.test.js
Labels: size/L

#398 THD-8264 USSD Repayment Balance check Issue
  CHANGELOG.md
  repayments-rw/repaymentsRw.js
  repayments-rw/repaymentsRw.test.js
  repayments-rw/translations/index.js
  rw-legacy/core.js
  rw-legacy/lib/cor-get-balance.js
  rw-legacy/lib/utils/message-translations.js
Labels: size/S

#399 THD-7443 Mobile Enrollment-Request change on Account Number SMS Feature-TZ
  CHANGELOG.md
  ke-registration-notification/registrationNotification.js
  ke-registration-notification/registrationNotification.test.js
  ke-registration-notification/translations/index.js
Labels: size/M

#377 ESWFA-197 Avocado ordering RW
  CHANGELOG.md
  avocado-trees-ordering/avocadoTreesOrdering.js
  avocado-trees-ordering/avocadoTreesOrdering.test.js
  avocado-trees-ordering/confirm-order-handler/confirmOrderHandler.js
  avocado-trees-ordering/confirm-order-handler/confirmOrderHandler.test.js
  avocado-trees-ordering/place-order-handler/placeOrderHandler.js
  avocado-trees-ordering/translations.js
  rw-legacy/core.js
  rw-legacy/enrollment.js
  rw-legacy/lib/core-group-size-check.js
  rw-legacy/lib/enr-check-gid.js
  rw-legacy/lib/enr-client-logger.js
  rw-legacy/lib/enr-group-leader-check.js
  rw-legacy/lib/utils/message-translations.js
Labels: size/L

#400 Deployment 12 aug 2021
  CHANGELOG.md
  avocado-trees-ordering/avocadoTreesOrdering.js
  avocado-trees-ordering/avocadoTreesOrdering.test.js
  avocado-trees-ordering/confirm-order-handler/confirmOrderHandler.js
  avocado-trees-ordering/confirm-order-handler/confirmOrderHandler.test.js
  avocado-trees-ordering/place-order-handler/placeOrderHandler.js
  avocado-trees-ordering/translations.js
  ke-legacy/main.js
  ke-registration-notification/registrationNotification.js
  ke-registration-notification/registrationNotification.test.js
  ke-registration-notification/translations/index.js
  regions_handler/ussd_google_message_script.js
  regions_handler/ussd_google_message_script.test.js
  repayments-rw/repaymentsRw.js
  repayments-rw/repaymentsRw.test.js
  repayments-rw/translations/index.js
  rw-legacy/core.js
  rw-legacy/enrollment.js
  rw-legacy/lib/cor-get-balance.js
  rw-legacy/lib/core-group-size-check.js
  rw-legacy/lib/enr-check-gid.js
  rw-legacy/lib/enr-client-logger.js
  rw-legacy/lib/enr-group-leader-check.js
  rw-legacy/lib/utils/message-translations.js
Labels: size/L

#385 ESWFA-209 KE: USSD Farmer Training Enrollment
  CHANGELOG.md
  ke-legacy/main.js
  kenya-impact-trainings/IPP-DUKA/inputHandlers/phoneNumberHandler.js
  kenya-impact-trainings/IPP-DUKA/inputHandlers/phoneNumberHandler.test.js
  kenya-impact-trainings/IPP-DUKA/kenya-impact-trainings.js
  kenya-impact-trainings/IPP-DUKA/kenya-impact-trainings.test.js
  kenya-impact-trainings/IPP-DUKA/translations/index.js
  kenya-impact-trainings/IPP-DUKA/utils/TrainingTriggeredText.js
  kenya-impact-trainings/IPP-DUKA/utils/TrainingTriggeredText.test.js
  kenya-impact-trainings/enrollment/inputHandlers/enrollmentTrainingsHandler.js
  kenya-impact-trainings/enrollment/inputHandlers/enrollmentTrainingsHandler.test.js
  kenya-impact-trainings/enrollment/trainings-enrollment.js
  kenya-impact-trainings/enrollment/trainings-enrollment.test.js
  kenya-impact-trainings/enrollment/translations/index.js
  kenya-impact-trainings/enrollment/utils/checkIfIPPClient.js
  kenya-impact-trainings/enrollment/utils/checkIfIPPClient.test.js
  kenya-impact-trainings/impact-trainings.js
  kenya-impact-trainings/impact-trainings.test.js
  kenya-impact-trainings/inputHandlers/impactTrainingsMenuHandler.js
  kenya-impact-trainings/inputHandlers/impactTrainingsMenuHandler.test.js
  kenya-impact-trainings/translations/index.js
  package-lock.json
  package.json
  registration-notification/registrationNotification.js
  registration-notification/registrationNotification.test.js
  registration-notification/translations/index.js
Labels: size/L

#401 resolving the issue with KE shs calling getshs price
  shs/helper-functions/getShsPrice.js
  shs/helper-functions/getShsPrice.test.js
Labels: size/S

#402 changing the way invalid inputs are handled
  CHANGELOG.md
  package-lock.json
  package.json
  rw-legacy/extension-survey.js
  rw-legacy/lib/ext-ask-question.js
  rw-legacy/lib/ext-survey-start.js
  rw-legacy/lib/utils/message-translations.js
Labels: size/L

#406 fixing pshop registration
  pshopRegistration/inputHandlers/districtHandler.js
  pshopRegistration/inputHandlers/districtHandler.test.js
  pshopRegistration/inputHandlers/groupHandler.js
  pshopRegistration/inputHandlers/groupHandler.test.js
  pshopRegistration/inputHandlers/sectorHandler.js
  pshopRegistration/inputHandlers/sectorHandler.test.js
  pshopRegistration/inputHandlers/sitesHandler.js
  pshopRegistration/inputHandlers/sitesHandler.test.js
  pshopRegistration/pshopRegistration.js
  pshopRegistration/pshopRegistration.test.js
  pshopRegistration/utils/registerClient.js
Labels: size/S

#407 Eswfa 231 fix seed germination
  seed-germination-issues/inputHandlers/customSeedVarietyInputHandler.js
  seed-germination-issues/inputHandlers/customSeedVarietyInputHandler.test.js
  seed-germination-issues/inputHandlers/lotCodeInputHandler.js
  seed-germination-issues/inputHandlers/lotCodeInputHandler.test.js
  seed-germination-issues/inputHandlers/plantingDateInputHandler.js
  seed-germination-issues/inputHandlers/plantingDateInputHandler.test.js
  seed-germination-issues/inputHandlers/severityInputHandler.js
  seed-germination-issues/inputHandlers/severityInputHandler.test.js
  seed-germination-issues/translations/index.js
Labels: size/L

#408 Back merge 25 aug 2021
  CHANGELOG.md
  ke-legacy/main.js
  kenya-impact-trainings/IPP-DUKA/inputHandlers/phoneNumberHandler.js
  kenya-impact-trainings/IPP-DUKA/inputHandlers/phoneNumberHandler.test.js
  kenya-impact-trainings/IPP-DUKA/kenya-impact-trainings.js
  kenya-impact-trainings/IPP-DUKA/kenya-impact-trainings.test.js
  kenya-impact-trainings/IPP-DUKA/translations/index.js
  kenya-impact-trainings/IPP-DUKA/utils/TrainingTriggeredText.js
  kenya-impact-trainings/IPP-DUKA/utils/TrainingTriggeredText.test.js
  kenya-impact-trainings/enrollment/inputHandlers/enrollmentTrainingsHandler.js
  kenya-impact-trainings/enrollment/inputHandlers/enrollmentTrainingsHandler.test.js
  kenya-impact-trainings/enrollment/trainings-enrollment.js
  kenya-impact-trainings/enrollment/trainings-enrollment.test.js
  kenya-impact-trainings/enrollment/translations/index.js
  kenya-impact-trainings/enrollment/utils/checkIfIPPClient.js
  kenya-impact-trainings/enrollment/utils/checkIfIPPClient.test.js
  kenya-impact-trainings/impact-trainings.js
  kenya-impact-trainings/impact-trainings.test.js
  kenya-impact-trainings/inputHandlers/impactTrainingsMenuHandler.js
  kenya-impact-trainings/inputHandlers/impactTrainingsMenuHandler.test.js
  kenya-impact-trainings/translations/index.js
  package-lock.json
  package.json
  pshopRegistration/inputHandlers/districtHandler.js
  pshopRegistration/inputHandlers/districtHandler.test.js
  pshopRegistration/inputHandlers/groupHandler.js
  pshopRegistration/inputHandlers/groupHandler.test.js
  pshopRegistration/inputHandlers/sectorHandler.js
  pshopRegistration/inputHandlers/sectorHandler.test.js
  pshopRegistration/inputHandlers/sitesHandler.js
  pshopRegistration/inputHandlers/sitesHandler.test.js
  pshopRegistration/pshopRegistration.js
  pshopRegistration/pshopRegistration.test.js
  pshopRegistration/utils/registerClient.js
  registration-notification/registrationNotification.js
  registration-notification/registrationNotification.test.js
  registration-notification/translations/index.js
  rw-legacy/extension-survey.js
  rw-legacy/lib/ext-ask-question.js
  rw-legacy/lib/ext-survey-start.js
  rw-legacy/lib/utils/message-translations.js
  seed-germination-issues/inputHandlers/customSeedVarietyInputHandler.js
  seed-germination-issues/inputHandlers/customSeedVarietyInputHandler.test.js
  seed-germination-issues/inputHandlers/lotCodeInputHandler.js
  seed-germination-issues/inputHandlers/lotCodeInputHandler.test.js
  seed-germination-issues/inputHandlers/plantingDateInputHandler.js
  seed-germination-issues/inputHandlers/plantingDateInputHandler.test.js
  seed-germination-issues/inputHandlers/severityInputHandler.js
  seed-germination-issues/inputHandlers/severityInputHandler.test.js
  seed-germination-issues/translations/index.js
  shs/helper-functions/getShsPrice.js
  shs/helper-functions/getShsPrice.test.js
Labels: size/XL

#409 ESWFA-231 Fix germination screens
  CHANGELOG.md
  ke-legacy/utils/menus/populate-menu/mainMenu.js
  ke-legacy/utils/menus/populate-menu/nonClientMainMenu.js
  ke-registration-notification/registrationNotification.js
  ke-registration-notification/registrationNotification.test.js
  ke-registration-notification/translations/index.js
  rw-legacy/core.js
  rw-legacy/lib/cor-get-balance.js
  rw-legacy/lib/cta-geo-select.js
  seed-germination-issues/inputHandlers/customSeedVarietyInputHandler.test.js
  seed-germination-issues/inputHandlers/plantingDateInputHandler.test.js
  seed-germination-issues/translations/index.js
Labels: size/L
