Repository one-acre-fund/ussd-sms, pull requests merged in 2021-06, with the labels that each got.

#337 HotFix-THD-442-Rw repayment fix sms route
  CHANGELOG.md
  package-lock.json
  package.json
  repayments-rw/repaymentsRw.js
Labels: size/XS

#339 append all played episodes and top tips in a call variable - ESWFA-175
  sbcc/ivr/input-handlers/mainMenuOneHandler.js
  sbcc/ivr/input-handlers/mainMenuTwoHandler.js
  sbcc/ivr/input-handlers/olderEpisodesMenuHandler1.js
  sbcc/ivr/input-handlers/olderEpisodesMenuHandler2.js
  sbcc/ivr/input-handlers/selectedTipAndEpHandler1.js
  sbcc/ivr/input-handlers/selectedTipAndEpHandler2.js
  sbcc/ivr/input-handlers/topTipsMenuHandler1.js
  sbcc/ivr/input-handlers/topTipsMenuHandler2.js
  sbcc/ussd/input-handlers/pinHandler.js
  sbcc/utils/addPlayedItem.js
  sbcc/utils/addPlayedItem.test.js
Labels: size/M

#336 Add Service to send SMS Notifications to Registered Clients - ESWFA-173
  CHANGELOG.md
  ke-registration-notification/registrationNotification.js
  ke-registration-notification/registrationNotification.test.js
  ke-registration-notification/translations/index.js
  package-lock.json
  package.json
  sbcc/ivr/input-handlers/mainMenuOneHandler.js
  sbcc/ivr/input-handlers/mainMenuTwoHandler.js
  sbcc/ivr/input-handlers/olderEpisodesMenuHandler1.js
  sbcc/ivr/input-handlers/olderEpisodesMenuHandler2.js
  sbcc/ivr/input-handlers/selectedTipAndEpHandler1.js
  sbcc/ivr/input-handlers/selectedTipAndEpHandler2.js
  sbcc/ivr/input-handlers/topTipsMenuHandler1.js
  sbcc/ivr/input-handlers/topTipsMenuHandler2.js
  sbcc/ussd/input-handlers/pinHandler.js
  sbcc/utils/addPlayedItem.js
  sbcc/utils/addPlayedItem.test.js
Labels: size/L

#340 Eswfa 174 avoid querying with null
  CHANGELOG.md
  rw-legacy/core.js
  rw-legacy/lib/enr-group-leader-check.js
  rw-legacy/lib/get-menu-option.js
Labels: size/S

#341 HOTFIX-rename RW repayment season to 2021
  CHANGELOG.md
  package-lock.json
  package.json
  repayments-rw/repaymentsRw.test.js
  repayments-rw/translations/index.js
Labels: size/S

#342 Eswfa 182 continue ordering
  CHANGELOG.md
  package-lock.json
  package.json
  rw-legacy/core.js
  rw-legacy/lib/utils/message-translations.js
Labels: size/S

#345 Eswfa 187 end enrollment in districts
  rw-legacy/core.js
  rw-legacy/lib/get-menu-option.js
  rw-legacy/lib/isDistrictClosed.js
  rw-legacy/lib/populate-menu.js
  rw-legacy/lib/utils/message-translations.js
Labels: size/M

#343 ESWFA-42-Add bu navigation
  CHANGELOG.md
  bu-ussd/enrollment/enrollment.js
  bu-ussd/enrollment/inputHandlers/finalizeHandler.js
  bu-ussd/enrollment/inputHandlers/finalizeHandler.test.js
  bu-ussd/enrollment/translations/index.js
  bu-ussd/enrollment/utils/confirmOrder.js
  bu-ussd/enrollment/utils/confirmOrder.test.js
  bu-ussd/enrollment/utils/onOrderOrFinaliseSelected.js
  bu-ussd/enrollment/utils/onOrderOrFinaliseSelected.test.js
  bu-ussd/inputHandlers/enrollmentCategoryHandler.js
  bu-ussd/inputHandlers/enrollmentCategoryHandler.test.js
  bu-ussd/inputHandlers/groupCodeHandler.js
  bu-ussd/inputHandlers/groupCodeHandler.test.js
  bu-ussd/inputHandlers/mainMenuHandler.js
  bu-ussd/inputHandlers/mainMenuHandler.test.js
  bu-ussd/inputHandlers/preEnrollmentHandler.js
  bu-ussd/inputHandlers/preEnrollmentHandler.test.js
  bu-ussd/inputHandlers/registerInputHandlers.js
  bu-ussd/main.js
  bu-ussd/translations/index.js
  shared/splitLongMenu.js
  shared/splitLongMenu.test.js
Labels: size/XL

#346 Ser 582 log sms failures
  CHANGELOG.md
  message/message-failures/logMessageFailure.js
  message/message-failures/logMessageFailure.test.js
  message/message-failures/queryMessageFailure.js
  message/message-failures/queryMessageFailure.test.js
  package-lock.json
  package.json
  rw-legacy/traffic-alert.js
  setupTests.js
Labels: size/L

#348 updating the rwanda survey
  CHANGELOG.md
  package-lock.json
  package.json
  rw-legacy/extension-survey.js
  rw-legacy/lib/get-menu-option.js
  rw-legacy/lib/populate-menu.js
Labels: size/S

#349 HOT-FIX - ESWFA-192 updating the tester pack
  rw-legacy/dat/surveys.js
  rw-legacy/lib/utils/message-translations.js
  tester-pack/confirmation/inputHandlers/receptionHandler.js
  tester-pack/confirmation/inputHandlers/receptionHandler.test.js
  tester-pack/confirmation/translations/index.js
Labels: size/S

#350 Back merge 25 june 21
  .eslintrc.js
  CHANGELOG.md
  ke-registration-notification/registrationNotification.js
  ke-registration-notification/registrationNotification.test.js
  ke-registration-notification/translations/index.js
  message/message-failures/logMessageFailure.js
  message/message-failures/logMessageFailure.test.js
  message/message-failures/queryMessageFailure.js
  message/message-failures/queryMessageFailure.test.js
  mobile-money-receipts/main.js
  mobile-money-receipts/main.test.js
  notifications/elk-notification/elkNotification.js
  package-lock.json
  package.json
  repayments-rw/repaymentsRw.js
  repayments-rw/repaymentsRw.test.js
  repayments-rw/translations/index.js
  repayments/repayments.js
  repayments/repayments.test.js
  rw-legacy/core.js
  rw-legacy/dat/district-bundles.js
  rw-legacy/dat/surveys.js
  rw-legacy/extension-survey.js
  rw-legacy/lib/cor-get-balance.js
  rw-legacy/lib/enr-group-leader-check.js
  rw-legacy/lib/get-menu-option.js
  rw-legacy/lib/isDistrictClosed.js
  rw-legacy/lib/populate-menu.js
  rw-legacy/lib/utils/message-translations.js
  rw-legacy/traffic-alert.js
  sbcc/ivr/input-handlers/mainMenuOneHandler.js
  sbcc/ivr/input-handlers/mainMenuOneHandler.test.js
  sbcc/ivr/input-handlers/mainMenuTwoHandler.js
  sbcc/ivr/input-handlers/mainMenuTwoHandler.test.js
  sbcc/ivr/input-handlers/olderEpisodesMenuHandler1.js
  sbcc/ivr/input-handlers/olderEpisodesMenuHandler1.test.js
  sbcc/ivr/input-handlers/olderEpisodesMenuHandler2.js
  sbcc/ivr/input-handlers/olderEpisodesMenuHandler2.test.js
  sbcc/ivr/input-handlers/selectedTipAndEpHandler1.js
  sbcc/ivr/input-handlers/selectedTipAndEpHandler1.test.js
  sbcc/ivr/input-handlers/selectedTipAndEpHandler2.js
  sbcc/ivr/input-handlers/selectedTipAndEpHandler2.test.js
  sbcc/ivr/input-handlers/topTipsMenuHandler1.js
  sbcc/ivr/input-handlers/topTipsMenuHandler1.test.js
  sbcc/ivr/input-handlers/topTipsMenuHandler2.js
  sbcc/ivr/input-handlers/topTipsMenuHandler2.test.js
  sbcc/ivr/ivrMain.js
  sbcc/ivr/ivrMain.test.js
  sbcc/ussd/input-handlers/nationalIdHandler.js
  sbcc/ussd/input-handlers/nationalIdHandler.test.js
  sbcc/ussd/input-handlers/pinHandler.js
  sbcc/utils/addPlayedItem.js
  sbcc/utils/addPlayedItem.test.js
  setupTests.js
  tester-pack/confirmation/inputHandlers/receptionHandler.js
  tester-pack/confirmation/inputHandlers/receptionHandler.test.js
  tester-pack/confirmation/translations/index.js
Labels: size/XXL
